eureka:
  client:
    register-with-eureka: true  
    fetch-registry: true
    
    service-url:
      defaultZone:  http://localhost:8761/eureka/


  instance:
    hostname: localhost
    
    
spring:
 application:
  name: API-GATEWAY

 cloud:
    gateway:
      routes:
      
      - id: PRODUCT-SERVICE                   #http://localhost:8181/api/v1/department
        uri: lb://PRODUCT-SERVICE
        predicates:
        - Path=/product/**
      
     
      

